#cloud-config

hostname: lunch-buddy-app-instance

runcmd:
  - curl -fsSL https://pgp.mongodb.com/server-7.0.asc | gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
  - echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
  - apt-get update
  - apt-get install -y mongodb-org
  - snap install node --classic
  - cd /home/ubuntu
  - git clone https://github.com/JureH/lunch-buddy.git
  - cd lunch-buddy
  - npm install

  # Start MongoDB service
  - service mongod start

  # Build and start the Node.js server in the background
  - npm start > express_server.log 2>&1 &

  # Navigate to the Angular app directory
  - cd angular

  # Install Angular dependencies
  - npm install -g @angular/cli
  - npm install

  # Build and start the Angular app
  - ng serve --host localhost --port 4200 > angular.log 2>&1 &
  - echo "Done!"
