#cloud-config

hostname: lunch-buddy-app-instance

runcmd:
  # Add mongoDB repo
  - curl -fsSL https://pgp.mongodb.com/server-7.0.asc | gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
  - echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
  # Install mongoDB
  - apt-get update
  - apt-get install -y mongodb-org
  # Install Node.js
  - snap install node --classic
  # Download app from git
  - cd /home/ubuntu
  - git clone https://github.com/JureH/lunch-buddy.git
  # Install app dependencies
  - cd lunch-buddy
  - npm install
  # Start MongoDB service and copy starter data
  - service mongod start
  - mongoimport --db LunchBuddy --collection Chats --file chats.json --jsonArray
  - mongoimport --db LunchBuddy --collection Users --file users.json --jsonArray
  - mongoimport --db LunchBuddy --collection Restaurants --file restaurants.json --jsonArray
  - mongoimport --db LunchBuddy --collection Choices --file choices.json --jsonArray
  - rm -rf data
  # Build and start the Node.js server in the background
  - npm start > express_server.log 2>&1 &
  # Navigate to the Angular app directory
  - cd angular
  # Install Angular dependencies
  - npm install -g @angular/cli
  - npm install
  # Build and start the Angular app in the background
  - ng serve > angular.log 2>&1 &

  - echo "Done!"
