version: "3.5"
services:
  angular-app:
    container_name: lunch-buddy-angular-app
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - web-dev-network

  node-api:
    container_name: lunch-buddy-node-api
    ports:
      - "3000:3000"
    image: lunch-buddy-server
    build: ./
    environment:
      - NODE_ENV=test
      - JWT_SECRET=mySecretPassword
    networks:
      - web-dev-network
    volumes:
      - node-api-data:/app/data

  mongo-db:
    image: mongo
    container_name: lunch-buddy-mongo-db
    ports:
      - "27017:27017"
    networks:
      - web-dev-network
    volumes:
      - mongo-data:/data/db
  
  redis:
    image: "redis:latest"
    container_name: lunch-buddy-redis
    ports:
      - "6379:6379"
    networks:
      - web-dev-network

networks:
  web-dev-network:
    name: lunch-buddy-network
    driver: bridge

volumes:
  node-api-data:
  mongo-data: