apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_SECRET: bXlTZWNyZXRQYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-uri
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6bXktcGFzc3dvcmRAbW9uZ29kYjoyNzAxNy9MdW5jaEJ1ZGR5